{% set name = "ubermag" %}
{% set version = "0.66.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 99489d6d998d9fc10545102ee65f3d4323d0b4255669cf6013a0cea3bd630b1f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - discretisedfield ==0.65.1
    - mag2exp ==0.62.1
    - micromagneticdata ==0.65.0
    - micromagneticmodel ==0.63.1
    - micromagnetictests ==0.63.0
    - mumax3c ==0.1
    - oommfc ==0.64.0
    - ubermagtable ==0.61.2
    - ubermagutil ==0.63.1

test:
  imports:
    - ubermag

  commands:
    - python -c "import sys; import ubermag; sys.exit(ubermag.test())"

about:
  home: http://ubermag.github.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Meta package for the Ubermag project.
  doc_url: https://ubermag.github.io/documentation/ubermag.html
  dev_url: https://github.com/ubermag/ubermag

extra:
  recipe-maintainers:
    - marijanbeg
    - fangohr
    - lang-m
    - samjrholt
    - swapneelap
